replicas: 1
cpu:
  requests: "100m"
  limits: "8000m"
memory:
  requests: "64Mi"
  limits: "16Gi"
serviceType: ClusterIP
image:
  Name: lsheiba/tensorflow-ls-devel-gpu
  Tag: latest
persistence:
    enabled: true
    storageClass: standard
    nfs:
      server: 192.168.1.55
      path: "/kuberlab/mnist"
    accessMode: ReadWriteMany
    size: 16Gi

