{{- if .Values.persistence.enabled -}}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: "{{ printf "%s-%s" .Release.Name .Chart.Name | trunc 24 }}"
  labels:
      heritage: {{.Release.Service | quote }}
      release: {{.Release.Name | quote }}
      chart: "{{.Chart.Name}}-{{.Chart.Version}}"
  annotations:
  {{- if .Values.persistence.storageClass }}
    volume.beta.kubernetes.io/storage-class: {{ .Values.persistence.storageClass | quote }}
  {{- else }}
  {{- if not .Values.persistence.nfs.server }}
    volume.alpha.kubernetes.io/storage-class: default
  {{- end }}
  {{- end }}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
  {{- if .Values.persistence.nfs.server }}
  selector:
    matchLabels:
      release: {{.Release.Name | quote }}
      chart: "{{ printf "%s-%s" .Release.Name .Chart.Name | trunc 24 }}"
  {{- end }}
{{- end -}}
